version: '3.1'
services:
    flask:
        image: my_flas_docker
        container_name: flask
        networks:
            my-network:
                aliases:
                    - flask-app
        ports:
            - 8080:5000
    nginx:
        image: nginx:1.13.7
        container_name: nginx
        volumes:
            - ./auth:/etc/nginx/conf.d
            - ./nginx.conf:/etc/nginx/conf.d/default.conf
        networks:
            - my-network
        ports:
            - 80:80
        depends_on:
            - flask    

networks:
    my-network:        

